In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
import torch
from sklearn.datasets import load_iris

In [2]:
a = 15
b = 20
type((2 * a + 3 * b)**2)

int

In [3]:
a = np.array([15])
b = np.array([20])
print((2 * a + 3 * b)**2)
type((2 * a + 3 * b)**2)

[8100]


numpy.ndarray

In [4]:
a = np.array([15, 3, 4, 7, -3])
b = np.array([20, 101, -2, 15, 19])
print((2 * a + 3 * b)**2)
type((2 * a + 3 * b)**2)

[ 8100 95481     4  3481  2601]


numpy.ndarray

#### Using tensorflow

In [5]:
a = tf.constant([15, 3, 4, 7, -3])
b = np.array([20, 101, -2, 15, 19])

In [6]:
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([15,  3,  4,  7, -3], dtype=int32)>

In [7]:
type((2 * a + 3 * b)**2)

tensorflow.python.framework.ops.EagerTensor

In [8]:
(2 * a + 3 * b)**2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 8100, 95481,     4,  3481,  2601], dtype=int32)>

In [9]:
((2 * a + 3 * b)**2).numpy()

array([ 8100, 95481,     4,  3481,  2601], dtype=int32)

#### Using torch

In [10]:
a = torch.tensor([15, 3, 4, 7, -3])
b = torch.tensor([20, 101, -2, 15, 19])
type((2 * a + 3 * b)**2)

torch.Tensor

In [11]:
iris_data = load_iris()

In [12]:
iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [13]:
iris_data["data"]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
iris_data["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
attributes, labels = iris_data["data"], iris_data["target"]

In [16]:
attributes.shape

(150, 4)

In [17]:
attributes.shape[1], len(set(labels))

(4, 3)

## Tensorflow

In [18]:
tf.keras.backend.clear_session()

In [19]:
model_tf = Sequential([
    # input layer
    Input((attributes.shape[1],)), 
    # output layer
    Dense(len(set(labels)), activation="softmax") 
])

In [20]:
model_tf.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model_tf.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [22]:
model_tf.fit(attributes, labels, batch_size=8, epochs=10)

Epoch 1/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 2.5307  
Epoch 2/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 2.3199 
Epoch 3/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 2.1150 
Epoch 4/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 1.8751 
Epoch 5/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0031 - loss: 1.8419     
Epoch 6/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0172 - loss: 1.7283     
Epoch 7/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0131 - loss: 1.6348     
Epoch 8/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0350 - loss: 1.5644     
Epoch 9/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0336 - loss: 1.4949     
Epoch 10/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1007 - loss: 1.4053     


In [23]:
tf.argmax(model_tf.predict(attributes), axis=1)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 


<tf.Tensor: shape=(150,), dtype=int64, numpy=
array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2,
       0, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0])>

In [24]:
model_tf.evaluate(attributes, labels)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0451 - loss: 1.4788      


[1.381708025932312, 0.10000000149011612]

## PyTorch

In [25]:
class LogisticRegressionPT(torch.nn.Module):
  def __init__(self):
    super(LogisticRegressionPT, self).__init__()
    self.layer = torch.nn.Linear(attributes.shape[1], len(set(labels)))
  def forward(self, x):
    x = torch.nn.functional.softmax(self.layer(x), dim=-1)
    return x

In [26]:
model_pt = LogisticRegressionPT()

In [27]:
attributes_pt = torch.FloatTensor(attributes)
labels_pt = torch.LongTensor(labels)

In [28]:
model_pt(attributes_pt)

tensor([[0.0053, 0.1821, 0.8127],
        [0.0075, 0.2181, 0.7744],
        [0.0076, 0.1974, 0.7950],
        [0.0090, 0.2178, 0.7732],
        [0.0054, 0.1757, 0.8189],
        [0.0041, 0.1661, 0.8297],
        [0.0078, 0.1864, 0.8058],
        [0.0060, 0.1951, 0.7988],
        [0.0108, 0.2268, 0.7624],
        [0.0072, 0.2212, 0.7717],
        [0.0041, 0.1741, 0.8219],
        [0.0071, 0.2018, 0.7911],
        [0.0078, 0.2223, 0.7699],
        [0.0099, 0.2036, 0.7865],
        [0.0025, 0.1399, 0.8576],
        [0.0025, 0.1277, 0.8698],
        [0.0037, 0.1454, 0.8509],
        [0.0054, 0.1787, 0.8159],
        [0.0035, 0.1750, 0.8215],
        [0.0048, 0.1652, 0.8299],
        [0.0049, 0.2069, 0.7882],
        [0.0052, 0.1683, 0.8265],
        [0.0062, 0.1548, 0.8390],
        [0.0068, 0.2036, 0.7896],
        [0.0077, 0.2214, 0.7708],
        [0.0074, 0.2316, 0.7610],
        [0.0065, 0.1941, 0.7993],
        [0.0051, 0.1878, 0.8071],
        [0.0051, 0.1886, 0.8062],
        [0.008